### ISSUE TITLE
Deserializing Rails api results may fail in ember 1.8

### ISSUE THREAD

**Issue by jeveloper** [abuiles/borrowers#1]
Be careful upgrading to 1.8 from 1.7
I discovered that ActiveModel adapter won't deserialize properly causing this error:

TypeError: undefined is not a function
at Object.func (http://localhost:4200/assets/vendor.js:49499:18)
at Object.Cache.get (http://localhost:4200/assets/vendor.js:25100:38)
at decamelize (http://localhost:4200/assets/vendor.js:49541:31)
at RESTSerializer.extend.keyForAttribute (http://localhost:4200/assets/vendor.js:63962:16)
at apply (http://localhost:4200/assets/vendor.js:32847:27)
at superWrapper as keyForAttribute
at null. (http://localhost:4200/assets/vendor.js:66421:31)
at null. (http://localhost:4200/assets/vendor.js:68910:20)
at cb (http://localhost:4200/assets/vendor.js:29082:22)
at OrderedSet.forEach (http://localhost:4200/assets/vendor.js:28880:13)

But once i switched back to 1.7 , it worked perfectly.

In fact I AM following your book and it simply wouldn't work in the very first chapter where you attempt to call your api and get first name from friends endpoint.

**Comment by abuiles** [comment]
@jeveloper did you add this line too when upgrading? https://github.com/abuiles/borrowers/commit/80e489109509f1a66d2f13a57c375435293af672#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R23
