### ISSUE TITLE
borrowers doesn't build clean

### ISSUE THREAD

**Issue by rabarar** [abuiles/borrowers#6]
I cloned the repo,
npm install
bower installl
and get the following warnings on npm install:

```

npm WARN engine makeerror@1.0.10: wanted: {"node":"0.6.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine tmpl@1.0.3: wanted: {"node":"0.6.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN unmet dependency /Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf requires glob@'^4.4.2' but will load
npm WARN unmet dependency /Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/glob,
npm WARN unmet dependency which is version 4.0.5
npm WARN unmet dependency /Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/broccoli-caching-writer/node_modules/rimraf requires glob@'^4.4.2' but will load
npm WARN unmet dependency /Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/glob,
npm WARN unmet dependency which is version 4.0.5
npm WARN unmet dependency /Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/sander/node_modules/rimraf requires glob@'^4.4.2' but will load
npm WARN unmet dependency /Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/glob,
npm WARN unmet dependency which is version 4.0.5
npm WARN unmet dependency /Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/rimraf requires glob@'^4.4.2' but will load
npm WARN unmet dependency /Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/glob,
npm WARN unmet dependency which is version 4.0.5
```

And then when I attempt to ember server:

```
version: 0.2.0-beta.1
Proxying to http://api.ember-cli-101.com
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
undefined is not a function
TypeError: undefined is not a function
    at rimraf (/Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:57:13)
    at lib$rsvp$node$$tryApply (/Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1467:11)
    at lib$rsvp$node$$handleValueInput (/Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1567:20)
    at fn (/Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1555:18)
    at /Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:100:14
    at lib$rsvp$$internal$$tryCatch (/Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/robert/src/ember/borrowers/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by abuiles** [comment]
oh, my repo might be busted, I'll updated to the latest.

Which node version are you using? Do you get the same error when doing ember new?

**Comment by rabarar** [comment]
node 0.12.0

ember new works…
